import { useEffect, useMemo, useState } from "react";
import jsPDF from "jspdf";
import { ChevronLeft, ChevronRight, Download, Plus, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  createCalendarEvent,
  formatDateKey,
  getCombinedCalendarEvents,
  getMonthDays,
  parseDateKey,
  saveCalendarEvents,
  type CalendarEvent,
  type CalendarEventType,
} from "@/services/calendar";

const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
const WEEKDAY_NAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

const EVENT_TYPE_META: Record<
  CalendarEventType,
  {
    label: string;
    chipClass: string;
    pdfFill: [number, number, number];
    pdfText: [number, number, number];
  }
> = {
  regular: {
    label: "Regular Event",
    chipClass: "bg-cyan-50 text-cyan-700",
    pdfFill: [231, 248, 250],
    pdfText: [8, 145, 178],
  },
  holiday: {
    label: "Holiday",
    chipClass: "bg-rose-50 text-rose-600",
    pdfFill: [255, 234, 238],
    pdfText: [225, 29, 72],
  },
  deadline: {
    label: "Deadline",
    chipClass: "bg-amber-50 text-amber-700",
    pdfFill: [255, 243, 205],
    pdfText: [180, 83, 9],
  },
  meeting: {
    label: "Meeting",
    chipClass: "bg-violet-50 text-violet-700",
    pdfFill: [243, 232, 255],
    pdfText: [124, 58, 237],
  },
  system_week: {
    label: "Week Label",
    chipClass: "bg-cyan-50 text-cyan-700",
    pdfFill: [231, 248, 250],
    pdfText: [8, 145, 178],
  },
};

function formatDateLabel(dateKey: string) {
  return parseDateKey(dateKey).toLocaleDateString(undefined, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
}

function drawMonthPdfPage(doc: jsPDF, monthDate: Date, eventMap: Map<string, CalendarEvent[]>, title: string) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 24;
  const gridTop = 86;
  const colWidth = (pageWidth - margin * 2) / 7;
  const rowHeight = 86;
  const days = getMonthDays(monthDate);

  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text(title, margin, 30);

  doc.setFontSize(15);
  doc.text(`${MONTH_NAMES[monthDate.getMonth()]} ${monthDate.getFullYear()}`, pageWidth / 2, 30, { align: "center" });

  doc.setFontSize(9);
  WEEKDAY_NAMES.forEach((day, index) => {
    doc.setTextColor(71, 85, 105);
    doc.text(day, margin + index * colWidth + 6, 58);
  });

  days.forEach((date, index) => {
    const x = margin + (index % 7) * colWidth;
    const y = gridTop + Math.floor(index / 7) * rowHeight;
    const dateKey = formatDateKey(date);
    const isCurrentMonth = date.getMonth() === monthDate.getMonth();
    const events = eventMap.get(dateKey) || [];

    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(isCurrentMonth ? 255 : 248, isCurrentMonth ? 255 : 250, isCurrentMonth ? 255 : 252);
    doc.rect(x, y, colWidth, rowHeight, "FD");

    doc.setFontSize(11);
    doc.setTextColor(isCurrentMonth ? 15 : 148, isCurrentMonth ? 23 : 163, isCurrentMonth ? 42 : 184);
    doc.text(String(date.getDate()), x + 6, y + 14);

    events.slice(0, 3).forEach((event, eventIndex) => {
      const eventY = y + 24 + eventIndex * 16;
      const meta = EVENT_TYPE_META[event.type];
      doc.setFillColor(...meta.pdfFill);
      doc.roundedRect(x + 5, eventY, colWidth - 10, 11, 2, 2, "F");
      doc.setFontSize(7);
      doc.setTextColor(...meta.pdfText);
      doc.text(event.title.slice(0, 24), x + 8, eventY + 8);
    });
  });

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Calendar Builder", pageWidth / 2, pageHeight - 10, { align: "center" });
}

type CalendarBuilderProps = {
  readOnly?: boolean;
};

export default function CalendarBuilder({ readOnly = false }: CalendarBuilderProps) {
  const [currentMonth, setCurrentMonth] = useState(() => new Date());
  const [selectedDates, setSelectedDates] = useState<string[]>([]);
  const [title, setTitle] = useState("");
  const [eventType, setEventType] = useState<Exclude<CalendarEventType, "system_week">>("regular");
  const [eventSearch, setEventSearch] = useState("");
  const [customEvents, setCustomEvents] = useState<CalendarEvent[]>(() =>
    getCombinedCalendarEvents([2025, 2026, 2027]).filter((event) => !event.system)
  );

  useEffect(() => {
    if (readOnly) return;
    saveCalendarEvents(customEvents);
  }, [customEvents, readOnly]);

  const monthDays = useMemo(() => getMonthDays(currentMonth), [currentMonth]);
  const allEvents = useMemo(() => {
    void customEvents;
    return getCombinedCalendarEvents([currentMonth.getFullYear() - 1, currentMonth.getFullYear(), currentMonth.getFullYear() + 1]);
  }, [customEvents, currentMonth]);

  const eventMap = useMemo(() => {
    const map = new Map<string, CalendarEvent[]>();
    allEvents.forEach((event) => {
      if (!map.has(event.date)) map.set(event.date, []);
      map.get(event.date)!.push(event);
    });
    return map;
  }, [allEvents]);

  const monthEvents = useMemo(
    () =>
      allEvents
        .filter((event) => {
          const date = parseDateKey(event.date);
          return date.getFullYear() === currentMonth.getFullYear() && date.getMonth() === currentMonth.getMonth();
        })
        .sort((a, b) => a.date.localeCompare(b.date) || a.title.localeCompare(b.title)),
    [allEvents, currentMonth]
  );
  const filteredMonthEvents = useMemo(() => {
    const query = eventSearch.trim().toLowerCase();
    if (!query) return monthEvents;
    return monthEvents.filter((event) => {
      const label = EVENT_TYPE_META[event.type].label.toLowerCase();
      return `${event.title} ${event.date} ${label}`.toLowerCase().includes(query);
    });
  }, [eventSearch, monthEvents]);

  const toggleDate = (dateKey: string) => {
    if (readOnly) return;
    setSelectedDates((current) =>
      current.includes(dateKey) ? current.filter((item) => item !== dateKey) : [...current, dateKey].sort()
    );
  };

  const handleAddEvents = () => {
    if (readOnly) return;
    if (!title.trim() || selectedDates.length === 0) return;

    const newEvents = selectedDates.map((date) => createCalendarEvent(date, title.trim(), eventType));
    setCustomEvents((current) => [...current, ...newEvents].sort((a, b) => a.date.localeCompare(b.date) || a.title.localeCompare(b.title)));
    setTitle("");
    setSelectedDates([]);
  };

  const handleDeleteEvent = (eventId: string) => {
    if (readOnly) return;
    setCustomEvents((current) => current.filter((event) => event.id !== eventId));
  };

  const handleExportMonthPdf = () => {
    const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
    drawMonthPdfPage(doc, currentMonth, eventMap, "Calendar Builder");
    doc.save(`${MONTH_NAMES[currentMonth.getMonth()].toLowerCase()}-${currentMonth.getFullYear()}-calendar.pdf`);
  };

  const handleExportYearPdf = () => {
    const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
    Array.from({ length: 12 }, (_, monthIndex) => monthIndex).forEach((monthIndex, index) => {
      const monthDate = new Date(currentMonth.getFullYear(), monthIndex, 1);
      if (index > 0) doc.addPage("a4", "landscape");
      drawMonthPdfPage(doc, monthDate, eventMap, `Calendar Builder ${currentMonth.getFullYear()}`);
    });
    doc.save(`${currentMonth.getFullYear()}-calendar-year.pdf`);
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <h2 className="text-xl font-semibold text-white sm:text-2xl">Calendar Builder</h2>
          <p className="mt-1 max-w-2xl text-sm text-slate-400">
            Select multiple dates, label them with events, and export the calendar for the month or full year.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" onClick={handleExportMonthPdf}>
            <Download className="mr-2 h-4 w-4" />
            Export Month PDF
          </Button>
          <Button variant="outline" onClick={handleExportYearPdf}>
            <Download className="mr-2 h-4 w-4" />
            Export Year PDF
          </Button>
        </div>
      </div>

      <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_320px]">
        <Card className="overflow-hidden rounded-2xl border-slate-700 bg-slate-900/50 shadow-sm">
          <CardHeader className="border-b border-slate-700 pb-4">
            <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
              <div>
                <CardTitle className="text-base font-semibold text-white sm:text-lg">Select Dates</CardTitle>
                <CardDescription className="text-slate-400">
                  Click multiple dates to build your calendar labels.
                </CardDescription>
              </div>

              <div className="flex items-center justify-between gap-2 rounded-xl border border-slate-600 bg-slate-800 px-2 py-2 sm:gap-3 sm:px-3">
                <Button variant="ghost" size="icon" onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1, 1))}>
                  <ChevronLeft className="h-4 w-4" />
                </Button>
                <div className="min-w-0 flex-1 text-center text-sm font-medium text-white sm:min-w-[160px] sm:text-base">
                  {MONTH_NAMES[currentMonth.getMonth()]} {currentMonth.getFullYear()}
                </div>
                <Button variant="ghost" size="icon" onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 1))}>
                  <ChevronRight className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </CardHeader>

          <CardContent className="p-4">
            <div className="grid grid-cols-7 border-b border-slate-700">
              {WEEKDAY_NAMES.map((day) => (
                <div key={day} className="px-2 py-3 text-center text-sm font-medium text-cyan-400">
                  {day}
                </div>
              ))}
            </div>

            <div className="grid grid-cols-7">
              {monthDays.map((date) => {
                const dateKey = formatDateKey(date);
                const isCurrentMonth = date.getMonth() === currentMonth.getMonth();
                const isSelected = selectedDates.includes(dateKey);
                const dayEvents = eventMap.get(dateKey) || [];

                return (
                  <button
                    key={dateKey}
                    type="button"
                    onClick={readOnly ? undefined : () => toggleDate(dateKey)}
                    className={`min-h-[84px] border-b border-r border-slate-700 px-1.5 py-2 text-left transition sm:min-h-[106px] sm:px-2 sm:py-3 ${
                      isSelected ? "bg-cyan-900/20" : readOnly ? "bg-slate-800/50" : "bg-slate-800/50 hover:bg-slate-700/50"
                    }`}
                  >
                      <div className={`flex h-7 w-7 items-center justify-center rounded-full text-xs sm:h-8 sm:w-8 sm:text-sm ${isSelected ? "bg-cyan-500 text-white" : isCurrentMonth ? "text-white" : "text-slate-500"}`}>
                        {date.getDate()}
                      </div>

                      <div className="mt-2 space-y-1 sm:mt-3">
                        {dayEvents.length === 0 ? (
                          <div className="h-3 rounded bg-slate-700 sm:h-4" />
                        ) : (
                          dayEvents.slice(0, 2).map((event) => (
                            <div key={event.id} className={`truncate rounded px-1.5 py-1 text-[10px] sm:px-2 sm:text-[11px] ${EVENT_TYPE_META[event.type].chipClass}`}>
                              {event.title}
                            </div>
                          ))
                      )}
                    </div>
                  </button>
                );
              })}
            </div>
          </CardContent>
        </Card>

        <div className="space-y-4">
          {!readOnly && (
            <Card className="rounded-2xl border-slate-700 bg-slate-900/50 shadow-sm">
              <CardHeader>
                <CardTitle className="text-white">Create Event</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <div className="mb-2 text-sm font-medium text-slate-300">Event Title</div>
                  <Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g., Week 1, Team Meeting" className="bg-slate-800 border-slate-600 text-white" />
                </div>

                <div>
                  <div className="mb-2 text-sm font-medium text-slate-300">Event Type</div>
                  <select
                    value={eventType}
                    onChange={(event) => setEventType(event.target.value as Exclude<CalendarEventType, "system_week">)}
                    className="h-11 w-full rounded-md border border-slate-600 bg-slate-800 px-3 text-sm text-white"
                  >
                    {Object.entries(EVENT_TYPE_META)
                      .filter(([key]) => key !== "system_week")
                      .map(([key, meta]) => (
                        <option key={key} value={key}>
                          {meta.label}
                        </option>
                      ))}
                  </select>
                </div>

                <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 p-3 text-sm text-slate-500">
                  {selectedDates.length > 0
                    ? `${selectedDates.length} date${selectedDates.length === 1 ? "" : "s"} selected`
                    : "Select one or more dates from the calendar"}
                </div>

                <Button className="w-full bg-slate-400 hover:bg-slate-500" onClick={handleAddEvents} disabled={!title.trim() || selectedDates.length === 0}>
                  <Plus className="mr-2 h-4 w-4" />
                  Add to {selectedDates.length || 0} Date(s)
                </Button>
              </CardContent>
            </Card>
          )}

          <Card className="rounded-2xl border-slate-200 bg-white shadow-sm">
            <CardHeader>
              <CardTitle>{readOnly ? "View Events" : "Manage Events"}</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="relative mb-3">
                <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                <Input
                  value={eventSearch}
                  onChange={(event) => setEventSearch(event.target.value)}
                  placeholder="Search events by title, date, or type..."
                  className="pl-9"
                />
              </div>
              <div className="max-h-[420px] space-y-2 overflow-y-auto pr-1">
                {filteredMonthEvents.length === 0 ? (
                  <div className="rounded-xl border border-dashed border-slate-600 p-4 text-sm text-slate-400">
                    {eventSearch.trim() ? "No events matched your search." : "No events yet for this month."}
                  </div>
                ) : (
                  filteredMonthEvents.map((event) => (
                    <div key={event.id} className="rounded-xl border border-slate-700 p-3">
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <div className="font-medium text-white">{event.title}</div>
                          <div className="mt-1 text-sm text-slate-400">{formatDateLabel(event.date)}</div>
                          <div className={`mt-2 inline-flex rounded px-2 py-1 text-[11px] ${EVENT_TYPE_META[event.type].chipClass}`}>
                            {EVENT_TYPE_META[event.type].label}
                          </div>
                        </div>
                        {event.system ? (
                          <div className="rounded-md bg-slate-700 px-2 py-1 text-[11px] text-slate-400">System</div>
                        ) : !readOnly ? (
                          <Button variant="ghost" size="icon" onClick={() => handleDeleteEvent(event.id)}>
                            <Trash2 className="h-4 w-4 text-red-400" />
                          </Button>
                        ) : null}
                      </div>
                    </div>
                  ))
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
